# Generated by Django 5.2.17 on 2026-08-12 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Démarrée le')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminée le')),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('SUCCESS', 'Réussie'), ('PARTIAL', 'Partielle'), ('FAILED', 'Échouée')], db_index=True, default='RUNNING', max_length=10, verbose_name='Statut')),
                ('media_type', models.CharField(blank=True, choices=[('ANIME', 'Animé'), ('MANGA', 'Manga')], max_length=10, null=True, verbose_name="Type d'œuvre")),
                ('criteria', models.JSONField(blank=True, null=True, verbose_name='Critères de collecte')),
                ('records_fetched', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Enregistrements récupérés')),
                ('records_created', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Enregistrements créés')),
                ('records_updated', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Enregistrements mis à jour')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
            ],
            options={
                'verbose_name': 'Journal de collecte',
                'verbose_name_plural': 'Journaux de collecte',
                'ordering': ['-started_at'],
            },
        ),
    ]
