# Generated by Django 5.2.17 on 2026-08-12 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anilist_id', models.IntegerField(unique=True, verbose_name='Identifiant AniList')),
                ('name_full', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet')),
                ('name_native', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom natif')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='Genre')),
                ('age', models.CharField(blank=True, max_length=50, null=True, verbose_name='Âge')),
            ],
            options={
                'verbose_name': 'Personnage',
                'verbose_name_plural': 'Personnages',
                'ordering': ['name_full'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anilist_id', models.IntegerField(unique=True, verbose_name='Identifiant AniList')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('is_animation_studio', models.BooleanField(default=False, verbose_name="Studio d'animation")),
            ],
            options={
                'verbose_name': 'Studio',
                'verbose_name_plural': 'Studios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anilist_id', models.IntegerField(unique=True, verbose_name='Identifiant AniList')),
                ('title_romaji', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre (romaji)')),
                ('title_english', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre (anglais)')),
                ('title_native', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre (natif)')),
                ('media_type', models.CharField(choices=[('ANIME', 'Animé'), ('MANGA', 'Manga')], db_index=True, max_length=10, verbose_name='Type')),
                ('format', models.CharField(blank=True, choices=[('TV', 'Série télévisée'), ('TV_SHORT', 'Série télévisée courte'), ('MOVIE', 'Film'), ('SPECIAL', 'Épisode spécial'), ('OVA', 'OVA'), ('ONA', 'ONA'), ('MUSIC', 'Vidéoclip'), ('MANGA', 'Manga'), ('NOVEL', 'Roman'), ('ONE_SHOT', 'One-shot')], max_length=20, null=True, verbose_name='Format')),
                ('status', models.CharField(blank=True, choices=[('FINISHED', 'Terminé'), ('RELEASING', 'En cours'), ('NOT_YET_RELEASED', 'Pas encore paru'), ('CANCELLED', 'Annulé'), ('HIATUS', 'En pause')], db_index=True, max_length=20, null=True, verbose_name='Statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('season', models.CharField(blank=True, choices=[('WINTER', 'Hiver'), ('SPRING', 'Printemps'), ('SUMMER', 'Été'), ('FALL', 'Automne')], max_length=10, null=True, verbose_name='Saison')),
                ('season_year', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Année de la saison')),
                ('episodes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'épisodes")),
                ('chapters', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de chapitres')),
                ('volumes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de volumes')),
                ('average_score', models.FloatField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score moyen')),
                ('popularity', models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Popularité')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image de couverture')),
                ('banner_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Bannière')),
                ('synopsis', models.TextField(blank=True, null=True, verbose_name='Synopsis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('genres', models.ManyToManyField(blank=True, related_name='media_items', to='catalog.genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Œuvre',
                'verbose_name_plural': 'Œuvres',
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='CharacterMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('MAIN', 'Principal'), ('SUPPORTING', 'Secondaire'), ('BACKGROUND', 'Arrière-plan')], max_length=20, null=True, verbose_name='Rôle')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='catalog.character', verbose_name='Personnage')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_links', to='catalog.media', verbose_name='Œuvre')),
            ],
            options={
                'verbose_name': 'Lien personnage-œuvre',
                'verbose_name_plural': 'Liens personnage-œuvre',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='characters', through='catalog.CharacterMedia', to='catalog.media', verbose_name='Œuvres'),
        ),
        migrations.CreateModel(
            name='MediaStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Studio principal')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_links', to='catalog.media', verbose_name='Œuvre')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='catalog.studio', verbose_name='Studio')),
            ],
            options={
                'verbose_name': 'Lien œuvre-studio',
                'verbose_name_plural': 'Liens œuvre-studio',
            },
        ),
        migrations.AddField(
            model_name='media',
            name='studios',
            field=models.ManyToManyField(blank=True, related_name='media_items', through='catalog.MediaStudio', to='catalog.studio', verbose_name='Studios'),
        ),
        migrations.AddConstraint(
            model_name='charactermedia',
            constraint=models.UniqueConstraint(fields=('character', 'media'), name='unique_character_media'),
        ),
        migrations.AddConstraint(
            model_name='mediastudio',
            constraint=models.UniqueConstraint(fields=('media', 'studio'), name='unique_media_studio'),
        ),
    ]
